#!/bin/bash

for (( i=1 ; i<=7 ; i++ ))
do
opencv_createsamples -img Positive_Images/pia$i.png -num 10 -bg Negative_Images/negatives.dat -info test$i.dat -maxxangle 0.6 -maxyangle 0 -maxzangle 0.3 -maxidev 100 -bgcolor 0 -bgthresh 0

done


